name: CI (Full)

on:
  pull_request:
    branches: [main]

jobs:
  full-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run full tests
        run: bash test/test_donburi.sh
